config/routes.rb
Rails.application.routes.draw do
    root "parts#index"

    resources :parts
	end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/part.rb
class Part < ApplicationRecord
# TODO: Add validation functionality 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
	@parts = Part.all
  end

  def show
	@part = Part.find(params[:id])
  end

  def new
	@part = Part.new
  end

  def create
		@part = Part.new(part_params)

		if @part.save
		  redirect_to @part
		else
		  render :new, status: :unprocessable_entity
		end
  end

  def edit
		@part = Part.find(params[:id])
	  end

	  def update
  		@part = Part.find(params[:id])

  		if @part.update(part_params)
  		  redirect_to @part
  		else
  		  render :edit, status: :unprocessable_entity
  		end
	  end

    def destroy
		  @part = Part.find(params[:id])
		  @part.destroy

		  redirect_to root_path
		end

  private
	def part_params
	  params.require(:part).permit(:manufacturer, :mpn, :description, :datasheet)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bauteile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parts/_form.html.erb
<%= form_with model: part do |form| %>
  <div>
  <%= form.label :manufacturer %><br>
  <%= form.text_field :manufacturer %>
  </div>

  <div>
  <%= form.label :mpn %><br>
  <%= form.text_field :mpn %>
  </div>

  <div>
  <%= form.label :description %><br>
  <%= form.text_field :manufacturer %>
  </div>

  <div>
  <%= form.label :datasheet %><br>
  <%= form.text_field :datasheet %>
  </div>

  <div>
  <%= form.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Edit Part</h1>
<%= render "form", part: @part %>
<%= link_to "Index", root_path %>

app/views/parts/index.html.erb
<h1>Parts</h1>

<table>
 <tr>
	 <th>Manufacturer</th>
	 <th>MPN</th>
	 <th>Decription</th>
	 <th>Datasheet(link)</th>
 </tr>
<% @parts.each do |part| %>
		<tr>
			 <th><a href="<%= part_path(part) %>"><%= part.manufacturer %></th>
			 <th><%= part.mpn %></th>
			 <th><%= part.description %></th>
			 <th><%= part.datasheet %></th>
		</tr>
	 <% end %>
</table>

<h1>Previous View:</h1>

<h1>Parts</h1>

<ul>
	  <% @parts.each do |part| %>
		  <li>
        <a href="<%= part_path(part) %>">
		    <%= part.manufacturer %>
        <%= part.mpn %>
        <%= part.description %>
        <%= part.datasheet %>
       </li>
		<% end %>
	</ul>

<%= link_to "New Part", new_part_path %>

app/views/parts/new.html.erb
<h1>New Part</h1>

	<%= form_with model: @part do |form| %>
	  <div>
		<%= form.label :manufacturer %><br>
		<%= form.text_field :manufacturer %>
	  </div>

	  <div>
		<%= form.label :mpn %><br>
		<%= form.text_field :mpn %>
	  </div>

	  <div>
		<%= form.label :description %><br>
		<%= form.text_field :manufacturer %>
	  </div>

	  <div>
		<%= form.label :datasheet %><br>
		<%= form.text_field :datasheet %>
	  </div>

	  <div>
		<%= form.submit %>
	  </div>
	<% end %>

app/views/parts/show.html.erb
<h1>Here is Part <%= @part.id %>!</h1>
<ul>
      <%= @part.manufacturer %>
      <%= @part.mpn %>
      <%= @part.description %>
      <%= @part.datasheet %>
      <%= link_to "Edit", edit_part_path(@part) %>
      <%= link_to "Destroy", part_path(@part),
  				          method: :delete,
  				          data: { confirm: "Are you sure?" } %>
</ul>